### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MuthukumarHelios** [biz/htmlpdf#1]
I am exploring your package and i have use one function which is written in that
[I use this function line](https://github.com/biz/htmlpdf/blob/master/htmlpdf.go#L48)
`
>case 1

```go
func main(){
html := `<h1 class="a">hello</h1>`
	//converting my html string to byte
      html_byte :=  []byte(html)
	htmlpdf.Create(html_byte)
}
```

---My Errors 
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x69d9a9]

goroutine 1 [running]:
github.com/biz/htmlpdf.(*PDF).Create(0x0, 0xc4200185e0, 0x18, 0x20, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/biz/htmlpdf/htmlpdf.go:72 +0x389
github.com/biz/htmlpdf.Create(0xc4200185e0, 0x18, 0x20, 0xc4200185e0, 0x18, 0x20)
	/home/user/go/src/github.com/biz/htmlpdf/htmlpdf.go:118 +0x4b
main.main()
	/home/user/projects/smart/feedback_app/src/test_app/main.go:33 +0x16d
exit status 2```

---
I need to convert my html to pdf is there is any way to do that in your source code

**Comment by james-maloney** [comment]
Do you have Google Chrome installed?

This package uses headless chrome to generate the PDF.

Sorry for the lack of docs, not really ready for prime time but it does get the job done if you have chrome installed and accessible from the command line.

**Comment by MuthukumarHelios** [comment]
terminal$google-chrome

My Google Chrome is working fine But it throws the below Error 

```
[4844:4881:0202/100257.265226:ERROR:browser_gpu_channel_host_factory.cc(107)] Failed to launch GPU process.
Created new window in existing browser session.
```

**Comment by james-maloney** [comment]
What is your OS? I've gotten this to work locally on a macOS and in a Docker image created from this Dockerfile https://github.com/jessfraz/dockerfiles/blob/master/chrome/stable/Dockerfile

**Comment by MuthukumarHelios** [comment]
hey @james-maloney Thank you for Reaching me Currently I am stuck with Some Work Will Reopen the issue After a Week once i give a Try
